### ISSUE TITLE
Pinned dependencies in pyproject.toml

### ISSUE THREAD

**Issue by jzazo** [sacdallago/bio_embeddings#119]
Hi! After installing bio_embeddings package I noticed that many of my dependencies downgraded, for example scikit-learn. I noticed that you upper bound many dependencies in `pyproject.toml`, and I would like to ask if such pins are necessary. Could some of those upper package versions be freed? Thank you.

**Comment by konstin** [comment]
Hi! Unfortunately restricting dependencies is necessary, as new major versions often break bio_embeddings or one of our dependencies. I do dependency updates from time to time, but without bounds `pip install bio_embeddings` will quickly end up in broken installations.

For the specific example of scikit-learn, there is an additional bound from PLUS. Since we already patch PLUS anyway I'll check if we can lift the bound there and upgrade scikit-learn.

**Comment by jzazo** [comment]
Thank you, I understand. However, it would be good practice to pin the bare minimum, and have tests to check that the package still works when the dependencies change.

**Comment by konstin** [comment]
It is crucial for bio_embeddings that `pip install bio_embeddings[all]` always works, so we unfortunately have to set strict upper limits and update them manually. In v0.1.7 I've updated scikit-learn to ^0.24.0, which I hope works for you.
