### ISSUE TITLE
Can't install version beyond 0.1.4

### ISSUE THREAD

**Issue by willfinnigan** [sacdallago/bio_embeddings#124]
Hi all,

Really great package!

I don't seem to be able to install any versions (with [all] specified), beyond 0.1.4.    Without [all] it works fine, but then I can't actually do anything.

When I try 0.1.5 - 0.1.7 I get this error:
```
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for bio-embeddings-bepler
Failed to build bio-embeddings-bepler
ERROR: Could not build wheels for bio-embeddings-bepler which use PEP 517 and cannot be installed directly
```

I think there is a problem with gcc on my mac which I havent been able to solve..  so this is probably my issue.  But I thought I'd let you know, since 0.1.4 works fine for me.

**Comment by sacdallago** [comment]
Hi @willfinnigan , thanks for reaching out! Since 0.1.4 we have introduced a new model that requires compliation upon installation (`bio-embeddings-bepler`). This is the Bepler model: https://github.com/bioembeddings/protein-sequence-embedding-iclr2019 . If you do not require this model, instead of `[all]`, you can install extras only for those models that are of interest to you, e.g. for protbert you have to install the general pipeline code `pip install bio_embeddings` and the extra for protbert `pip install bio_embeddings[transformers]`. All extras can be found here: https://github.com/sacdallago/bio_embeddings/blob/develop/pyproject.toml#L75 .

Thanks to you it's clear to me that we are missing fundamental clarifications in the documentation for the installation of the various embedders, aso we'll have a look at this soon!

In the meantime, apart from selectively picking which extras to install, you can solve the problem by -indeed- installing your mac's gcc compiler. In the olden days, if you just typed `gcc` or `git` in the terminal on osx, the OS would automatically detect that you are trying to use GCC and prompt you to install it, together with some xcode dependencies (like git).

**Comment by sacdallago** [comment]
Closing in favour of #125
