### ISSUE TITLE
Installation produces errors, imports don't work

### ISSUE THREAD

**Issue by LiorZ** [sacdallago/bio_embeddings#128]
This is the message that appears during installation:
```
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.2.1 which is incompatible.
ERROR: requests 2.23.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.4 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.4 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: bio-embeddings-tape-proteins 0.4 has requirement torch<1.8,>=1.0, but you'll have torch 1.8.1+cu101 which is incompatible.
ERROR: bio-embeddings-cpcprot 0.0.1 has requirement lmdb<2.0,>=1.0, but you'll have lmdb 0.99 which is incompatible.
ERROR: bio-embeddings-cpcprot 0.0.1 has requirement scipy<2.0,>=1.5, but you'll have scipy 1.4.1 which is incompatible.
```

Then, trying to import:
`from bio_embeddings.embed import BertEmbedder`
produces the following error:
`TypeError: Params.pop: key must be a supertype of `<class 'inspect._empty'> but is `<class 'str'>``

Link to Colab for reproduction: https://colab.research.google.com/drive/1msZVwcCT2b768HnbRK3SrnmRqtVjvsgg?

**Comment by sacdallago** [comment]
Hi @LiorZ , thanks for using `bio_embeddings`. It seems like the code you are trying to run is very outdated. Since that version of the code:

1. Colab has been updated in key components (python/pip)
2. Our pipeline has been updated to try to account for those changes
3. Out notebooks were updated to address some of those issues

Here you can find a mix of what you are trying to achieve on the latest version of the code: [extract supervised using seqvec](https://docs.bioembeddings.com/v0.1.6/notebooks/extract_supervised_from_seqvec.html).

Note that in my recent experience you need to execute the first block **twice** before colab is happy with everything. I'm talking about this block:
```
!pip3 install -U pip > /dev/null
!pip3 install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git" > /dev/null
```

If you want to use ProtBert (previously just "bert") instead of SeqVec:

```
from bio_embeddings.embed import ProtTransBertBFDEmbedder
embedder = ProtTransBertBFDEmbedder()
```

For the feature weights, instead of:
```
annotations_extractor = BasicAnnotationExtractor(
    secondary_structure_checkpoint_file="secstruct_checkpoint.pt",
    subcellular_location_checkpoint_file="subcell_checkpoint.pt"
)
```

you can simply type:
```
annotations_extractor = BasicAnnotationExtractor('seqvec_from_publication')
```
for SeqVec, or

```
annotations_extractor = BasicAnnotationExtractor('bert_from_publication')
```
for ProtBert.

The above will download all neccessary files for you (no need for those pesky `!wget` instructions anymore!

**Comment by LiorZ** [comment]
Hi @sacdallago !
Thanks for making such a great library!

I have ran the installation statements twice as you suggested.

Unfortunately I still encounter an error upon importing the library. Just running the following lines (on colab, and even locally using a clean conda environment with python 3.8.5):
`from bio_embeddings.embed import ProtTransBertBFDEmbedder`

`TypeError: Params.pop: key must be a supertype of <class 'inspect._empty'> but is <class 'str'>`
attached is a complete stack trace of the error
[stack_trace.txt](https://github.com/sacdallago/bio_embeddings/files/6403797/stack_trace.txt)

**Comment by LiorZ** [comment]
OK, Apparently, installing allenlp==2.2.0 solves the issue

**Comment by sacdallago** [comment]
Thanks @LiorZ ... 🤔 Colab remains a mystery. Sometimes it works, sometimes it doesn't.

Unfortunately we are users (just like everyone else) and can't really determine python/pip/underlying packages versions, this makes "reamining compatible" several magnitudes more challanging, and even for something that worked 1 day before, there's no guarantee it will work tomorrow.

Therefore my suggestion is always to run things locally when possible! But I'm glad you got it to work, and I'm sorry it's not as straightforward as we'd all hope.

**Comment by mkorpela** [comment]
Please update to overrides 6.1.0 that resolves third party untyped override.

**Comment by konstin** [comment]
@mkorpela I pinned overrides<5 since that is what allennlp needs.
