### ISSUE TITLE
HTTPError: HTTP Error 406: Not Acceptable SeqVecEmbedder

### ISSUE THREAD

**Issue by nprime496** [sacdallago/bio_embeddings#156]
Hi everyone, I'm trying to instantiate `bio_embeddings.embed.SeqVecEmbedder` but it outputs an HTTP error : 

![Screenshot from 2021-08-29 19-48-18](https://user-images.githubusercontent.com/54849528/131262015-9c173391-b892-4533-8493-fa7d0b87172e.png)

**Comment by ddofer** [comment]
I'm getting the exact same error, for all the embedding models.

**Comment by Xinxinatg** [comment]
Same here.

**Comment by sacdallago** [comment]
Hi, thanks for spotting. Let me have a look.

The issue here is that weights of the models cannot be downloaded. It seems that the server where weights are stored is up: http://data.bioembeddings.com/public/embeddings/embedding_models/

if you have neccessity to run experiments right now, I suggest you download the weights right now and pass them to the constructor of the embedder. E.g. for seqvec, that's "wegihts_file" and "options_file", from [here](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/seqvec_embedder.py#L32).




================

### Issue documentation

- Server is up
- Direct downloads work
- MD5 file hashes confirm file integrity
- [defaults](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/utilities/defaults.yml) looks fine
- direct request fails on same error:
  ```
  from urllib import request
  url = "http://data.bioembeddings.com/public/embeddings/embedding_models/seqvec/weights.hdf5"
  request.urlretrieve(url, filename="test")
  ```
  > HTTPError: HTTP Error 406: Not Acceptable
- Acccording to what I read online, we need to pass an additional header to the request. I think Arvixe might have blocked non-browser requests for some reason. Investigating...
- Changing the request system will work. Must add user-agent header

**Comment by ddofer** [comment]
Is there a way to load downloaded weights/options with the python package (instead of using the preconfigured config files)? 
(I couldn't find that in the documentation).
(My pipeline is already  set up with that, not yaml configs.  i.e `embedder = ProtTransBertBFDEmbedder(half_model=True)`

Thanks!

**Comment by sacdallago** [comment]
@ddofer yes, you simply pass the path to the constructor with the name of what it is.

```
embedder = ProtTransBertBFDEmbedder(half_model=True, model_directory="/path/to/weights/directory")
```

in this case, `/path/to/weights/directory` is the unzipped directory you fish from: http://data.bioembeddings.com/public/embeddings/embedding_models/bert/

Which files to download and what they are called (to pass it to the constructor) can be found here: https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/utilities/defaults.yml

**Comment by ddofer** [comment]
Thanks!
(I just came to delete this comment, after I made that same workaround myself before your reply :))

**Comment by konstin** [comment]
Can confirm:

Fails:

```
curl -H "User-Agent: Python-urllib/3.8" http://data.bioembeddings.com/public/embeddings/feature_models/prott5cons/checkpoint.pt
```

Works:

```
curl -H "User-Agent: Example/1.2.3" http://data.bioembeddings.com/public/embeddings/feature_models/prott5cons/checkpoint.pt
```

**Comment by sacdallago** [comment]
@konstin [this is what we'd need to change](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/utilities/remote_file_retriever.py#L75), to something like:

```
import urllib
import shutil

url = "http://data.bioembeddings.com/public/embeddings/embedding_models/seqvec/weights.hdf5"

req = request.Request(url, headers={
    'User-Agent' : 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)'
})

with urllib.request.urlopen(req) as response, open(outfile_path, 'wb') as outfile:
    shutil.copyfileobj(response, outfile)
```

The only issue is tqdm

**Comment by sacdallago** [comment]
I'll fix this for now and we'll see about tqdm later

**Comment by sacdallago** [comment]
@nprime496 @ddofer @Xinxinatg this issue should be solved with the latest version in develop. Please install using:

```
pip install -U "bio-embeddings[all] @ git+https://github.com/sacdallago/bio_embeddings.git"
``` 

We need to re-implement the progress bar (tqdm).
