### ISSUE TITLE
Take too long to initialize an embedder function

### ISSUE THREAD

**Issue by DeepColin** [sacdallago/bio_embeddings#169]

**Comment by sacdallago** [comment]
Hi @DeepColin ,

thanks for using bio-embeddings, and sorry for the late reply! Could you be a bit more specific on the issue? The models need to be downloaded first, and depending on the model, these might be several GBs. Once on disk, they need to be mounted on RAM/vRAM which adds additional time cost. These things we can't optimize.

If you note any slow down on operations that could otherwise be optimized, I fear that currently we can't make things go much faster!
