### ISSUE TITLE
Integrate UniRep

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#31]
https://www.biorxiv.org/content/10.1101/589333v1

Notice that UniRep has been re-engineered. Look for "jax-unirep":

From an ISMB comment:
> It might be of interested to check out jax-unirep, which is a re-implementation of the model that is much easier to work with than the tensorflow model

**Comment by konstin** [comment]
Now published as https://www.nature.com/articles/s41592-019-0598-1

Original repo: https://github.com/churchlab/UniRep

Jax-rewrite: https://github.com/ElArkk/jax-unirep

Docs: https://elarkk.github.io/jax-unirep/getting-started/

jax-unirep requires python 3.7. Given that this isn't due to some dependency requiring 3.7, we can ask the authors to relax the requirement to 3.6. 

jax from pypi by default is cpu and requires some workarounds for GPU support (https://github.com/google/jax#pip-installation).

**Comment by sacdallago** [comment]
Same as https://github.com/sacdallago/bio_embeddings/issues/22#issuecomment-675340922
