### ISSUE TITLE
Fix embed module when the extras aren't selected

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#51]
Currently using `from bio_embeddings.embed import ...` will lead to import errors when not using the `all` extra. This should be fixed by using try-except-ImportError-blocks and should be documented.

**Comment by sacdallago** [comment]
We might want to create a new test case, similar to `simple_pipeline_run`, where we just execute say `project` and `visualize` based on some pre-computed embeddings and by installing the pipeline without the `[all]`.

Currently, I'm wondering what will be installed if not selecting [all] (and per-effect: what installing the pipeline will buy a user).


We may want to make a simple `pip install bio-embeddings` install at least one embedder (SeqVec?) so that at least the most basic example (use_case_one?) would work!.

My fear: many people won't know what the `[all]` means at the end of `pip install xxx`. Especially considering that many users don't really know python or pip.

Another point: the expectation should be minimum amount of steps, as quick as possible. I expect the average user to do this:

1. Install
2. Run one of the examples
3. Change sequence file
4. Re-run example on my sequence file

The users shouldn't be bothered with too many options between these steps
