### ISSUE TITLE
Problem with embed_many() method

### ISSUE THREAD

**Issue by deniseduma** [sacdallago/bio_embeddings#83]
Hi again,

There seems to be an issue with your method embed_many() as called in the notebook embed_fasta_sequences.ipynb

Basically after these two calls 

embeddings = embedder.embed_many([str(s.seq) for s in sequences])
reduced_embeddings = [ProtTransBertBFDEmbedder.reduce_per_protein(e) for e in embeddings]

one can print the shape of embeddings or reduced_embeddings but not both! One of the lists is simply empty. 

You can check it for yourself by running the last cell which doesn't display anything. 

for (per_amino_acid, per_protein) in zip(embeddings, reduced_embeddings):
    print(per_amino_acid.shape, per_protein.shape)

The problem seems to go away when replacing embed_many() by calling embed() in a for loop.

Denise

**Comment by sacdallago** [comment]
Hi Denise,

thanks for rising this. In a recent update, @konstin changed the return type of `embed_many` from a list to a generator. This is desireble since the embeddings for large datasets can occupy significant RAM space, so storing the list might lead to RAM issues. When using generators, the generator is traversed and sequences are embedded on the fly. Once the generator is traversed, the generator is empty (so, in the current version of the notebook, "reduced_embeddings" will be populated, but "embeddings" will not, thus not printing anything in the last line).

The have the desired behaviour one should wrap `embed_many` in a list, aka:
```
embeddings = embedder.embed_many([str(s.seq) for s in sequences])
```
to
```
embeddings = list(embedder.embed_many([str(s.seq) for s in sequences]))
```

I've made this change and updated the notebook:

- [Here you can find the raw notebook](https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/embed_fasta_sequences.ipynb)
- [Here you can execute the notebook on Colab](https://colab.research.google.com/github/sacdallago/bio_embeddings/blob/develop/notebooks/embed_fasta_sequences.ipynb)


P.S.: just in case you are building up on this: we advice to use `embed` in a for loop as scarcely as possible.`embed_many` will embed your sequences in a batch (which is computationally more efficient than single sequence embeddings in a for loop!).

**Comment by deniseduma** [comment]
Ok, this makes sense! Thanks for the info!
