### ISSUE TITLE
ESM has no fallback

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#90]
ESM crashes with embed_many when out of memory instead of falling back to single sequence processing. Currently, only `EmbedderWithFallback` falls back to single sequence processing, but we can only use this superclass with a cpu fallback. This will also effect other embedders outside SeqVec/ProtTrans.

**Comment by sacdallago** [comment]
But isn't ESM pure pytorch? Shouldn't the fallback option in this case be a "simple" `model.to(cpu)`, then move on from where it crashed? Ultimately all the model weights _just_ need to be moved to CPU.

I mean, it's more convoluted because in your current `EmbedderWithFallback` implementation you have the first try the same batch, then try single sequence, then try single sequence CPU, then fail-fail, but you get my point :)

**Comment by konstin** [comment]
You're right, we can actually port all the models that batch to EmbedderWithFallback (the exceptions are bepler and unirep which do not batch).

**Comment by sacdallago** [comment]
Is this still relevant? I mean: yes (it's a fact), but can we close the issue if it's mitigated in the code (through rising errors or what not :))?

@konstin

**Comment by konstin** [comment]
I just tried very hard, but at least ESM1b categorically doesn't want to use more than 4GB so ¯\_(ツ)_/¯
